CREATE EXTENSION IF NOT EXISTS "uuid-ossp";
CREATE TABLE users
(
    uuid          UUID DEFAULT uuid_generate_v4(),
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
    login         VARCHAR(50)                             NOT NULL UNIQUE,
    name          VARCHAR(50)                             NOT NULL,
    surname       VARCHAR(50)                             NOT NULL,
    role          VARCHAR(50)                             NOT NULL,
    email         VARCHAR(320)                            NOT NULL UNIQUE,
    password      VARCHAR(50)                             NOT NULL,
    cost_per_hour NUMERIC                                 NOT NULL,
    projects_id   BIGINT
);
CREATE TABLE projects
(
    uuid        UUID DEFAULT uuid_generate_v4(),
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
    name        VARCHAR(50)                             NOT NULL UNIQUE,
    description VARCHAR(1000),
    start_date  TIMESTAMP,
    end_date    TIMESTAMP,
    budget      NUMERIC CHECK (BUDGET > 0),
    users_id    BIGINT
);
CREATE TABLE project_user
(
    project_id BIGINT NOT NULL,
    user_id    BIGINT NOT NULL,
    enter_on   TIMESTAMP,
    leave_on   TIMESTAMP,
    PRIMARY KEY (project_id, user_id),
    foreign key (user_id) references users (id)
        on delete cascade,
    foreign key (project_id) references projects (id)
        on delete cascade
);

create table time_records
(
    uuid       uuid default uuid_generate_v4(),
    id         bigint generated by default as identity primary key,
    start      timestamp,
    stop       timestamp,
    project_id bigint
        references projects,
    user_id    bigint
        references users
);

alter table users
    ADD FOREIGN KEY (projects_id) REFERENCES project_user (project_id);

alter table projects
    ADD FOREIGN KEY (users_id) REFERENCES project_user (user_id);
